inherit_gem:
  relaxed-rubocop: .rubocop.yml

AllCops:
  TargetRubyVersion: 2.6
  UseCache: true
  DefaultFormatter: progress
  DisplayStyleGuide: true
  DisplayCopNames: true
    - '**/*.rb'
    - '**/*.gemfile'
    - '**/*.gemspec'
    - '**/*.rake'
    - '**/*.ru'
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
    - "**/external/bundle/**/*"
    - "**/bazel-*/**/*"
    - "**/examples/**/*"
    - "**/BUILD"
    - "**/.bazel"
    - "**/vendor/bundle/**/*"

Layout/HashAlignment:
  Enabled: true
  EnforcedColonStyle: table
