# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.6.5

    working_directory: /home/circleci/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "ruby/gems/hello_world/Gemfile.lock" }}

      - run:
          name: install dependencies
          command: |
            cd /home/circleci/repo/ruby/gems/hello_world 
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - /home/circleci/repo/ruby/gems/hello_world/vendor/bundle
          key: v1-dependencies-{{ checksum "ruby/gems/hello_world/Gemfile.lock" }}

      - run:
          name: bundle install
          command: |
            cd /home/circleci/repo/ruby/gems/hello_world
            bundle install

      - run:
          name: run rspecs
          command: |
            cd /home/circleci/repo/ruby/gems/hello_world
            bundle exec rspec

      - run:
          name: run rubocop
          command: |
            cd /home/circleci/repo/ruby/gems/hello_world
            bundle exec rubocop -E -P
