# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5
    working_directory: /home/circleci/repo
    environment:
      HELLO_WORLD_PATH: /home/circleci/repo/ruby/gems/hello_world

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "ruby/gems/hello_world/Gemfile.lock" }}
      - run:
          name: Install Bundled Dependencies
          command: |
            cd ${HELLO_WORLD_PATH} && bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ${HELLO_WORLD_PATH}/vendor/bundle
          key: v1-dependencies-{{ checksum "${HELLO_WORLD_PATH}/Gemfile.lock" }}

      - run:
          name: Run Bundler
          command: |
            cd ${HELLO_WORLD_PATH} && bundle check || bundle install

      - run:
          name: Run RSpecs
          command: |
            cd ${HELLO_WORLD_PATH} && bundle exec rspec -p 2

  style:
    docker:
      - image: circleci/ruby:2.6.5
    working_directory: /home/circleci/repo
    environment:
      HELLO_WORLD_PATH: /home/circleci/repo/ruby/gems/hello_world

    steps:
      - checkout
      - run:
          name: "Run RuboCop, but Skip Bundle Install"
          command: |
            cd ${HELLO_WORLD_PATH}
            function gem.lock.version() { grep " $1 (" Gemfile.lock | awk '{print $2}' | tr -d '()'; }
            gem install rubocop --version $(gem.lock.version rubocop) --no-doc
            gem install relaxed-rubocop --version $(gem.lock.version relaxed-rubocop) --no-doc
            rubocop -E -P

  bazel:
    docker:
      - image: circleci/ruby:2.6.5
    working_directory: /home/circleci/repo
    environment:
      HELLO_WORLD_PATH: /home/circleci/repo/ruby/gems/hello_world
    steps:
      - checkout
      - run:
          name: "Linux Build Environment"
          command: |
            sudo apt-get update
            sudo apt-get install --reinstall build-essential

      - run:
          name: " ✅   Setup Bazel and Dependencies"
          command: |
            /usr/bin/env bash bin/setup

      - run:
          name: "Install Some Twinkie Crapola with Native Extensions"
          command: |
            gem install jaro_winkler -v '1.5.4' --verbose

      - run:
          name: " ✅   Bazel Build"
          command: |
            bazel build //...:all
            bazel query //...:all

      - run:
          name: " ✅    Run HelloWorld CLI via Bazel"
          command: |
            bazel run //ruby/gems/hello_world:cli spanish
            bazel run //ruby/gems/hello_world:cli japanese

      - run:
          name: " ✅   Run HelloWorld SPECS via Bazel"
          command: |
            bazel run //ruby/gems/hello_world:specs

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - style
      - bazel
