# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2.1
jobs:
  rspec: &bazel_defaults
    docker:
      - image: bazelruby/ruby-2.6.5
    working_directory: /home/circleci/repo
    environment:
      HOME: /home/circleci
      REPO_PATH: /home/circleci/repo
      HELLO_WORLD_PATH: /home/circleci/repo/ruby/gems/hello_world
      PATH: "/usr/local/bin:/usr/bin:/sbin:/opt/bin:/home/circleci/repo/bin:/bin:/sbin:/usr/sbin:${PATH}"
      BUNDLE_PATH: /home/circleci/.bundle_cache
      BAZEL_OPTS: "--host_jvm_args=-Xmx400m --host_jvm_args=-Xms400m"
      BAZEL_BUILD_OPTS: "--curses=no --verbose_failures --jobs 10"
      BAZEL_TEST_OPTS: "--verbose_failures --test_output=streamed --test_verbose_timeout_warnings "

    steps:
      - checkout

      - run:
          name: Run Setup
          command: |
            cd ${REPO_PATH}
            pwd -P
            /usr/bin/env bash bin/setup || true

      - run:
          name: Run RSpecs
          command: |
            cd ${HELLO_WORLD_PATH} && bundle exec rspec -p 2

  rubocop:
    <<: *bazel_defaults

    steps:
      - checkout

      - run:
          name: Run Setup
          command: |
            cd ${REPO_PATH}
            /usr/bin/env bash bin/setup || true

      - run:
          name: "Run Ruby Style Check"
          command: |
            cd /home/circleci/repo
            bundle install --path=${HOME}/.bundle/gems
            bundle exec rubocop -E -P

      - run:
          name: " Check if GCC/CC are installed"
          command: |
            set +e
            which gcc
            which cc
            which cc1
            cc --version  || true
            cc1 --version || true
            gcc --version || true

  bazel:
    <<: *bazel_defaults
    steps:
      - checkout

      - run:
          name: Run Setup
          command: |
            cd ${REPO_PATH}
            /usr/bin/env bash bin/setup || true

      - run:
          name: "Bazel Build"
          command: |
            bazel query //...:all
            echo
            bazel ${BAZEL_OPTS} build ${BAZEL_BUILD_OPTS}  //...:all

      - run:
          name: "Bazel Run CLI"
          command: |
            bazel ${BAZEL_OPTS} run ${BAZEL_BUILD_OPTS} //ruby/gems/hello_world:cli spanish japanese turkish russian

      - run:
          name: "Bazel Test"
          command: |
            bazel ${BAZEL_OPTS} test ${BAZEL_BUILD_OPTS} ${BAZEL_TEST_OPTS} //ruby/gems/hello_world:specs

      - run:
          name: "Build Sinatra App with Bazel"
          command: |
            bazel ${BAZEL_OPTS} build ${BAZEL_BUILD_OPTS} //ruby/apps/hello-world-web:all

      - run:
          name: "Run Rubocop using Bazel on all of the repo files using parent .rubocop.yml"
          command: |
            bazel ${BAZEL_OPTS} run //ruby:rubocop || true

workflows:
  version: 2
  build_and_test:
    jobs:
      - rspec
      - rubocop
      - bazel
